---
title: "Exercises 8"
author: "Your name"
date: "2024-10-07"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Exercises 9

```{r preamble}
library(tidyverse)
```

### 1. Load the data called dat.nsduh.small.csv.

```{r load-data}
dat <- read_csv("data/dat.nsduh.small.csv")
```

### 2. 

```{r}
dat %>% ggplot(aes(x=cigage, y=mjage)) + geom_point()

```

### 3. 

```{r linear-model}
out <- lm(mjage ~ cigage + iralcage, data = dat)
summary(out)

plot(out)
library(MASS)
plot(dat$mjage, dat$cigage)
# identify(dat$mjage, dat$cigage, tolerance=1, n=3)

dat$id <- 1:nrow(dat)

dat <- dat %>% 
    mutate(highlight = ifelse(row_number() %in% 15, "highlight", "normal"))

g <- dat %>% ggplot(aes(cigage, mjage)) +
    geom_point(aes(colour = highlight))

```

### 4. Draw the diagnostic plots for the model. What do you see regarding the assumptions? 

```{r diagnostic-plots}
plot(out)
```


### 5. Try out different transformations, ^2, ^.5, log.

```{r transformations}
dat <- read_csv("data/penguin_dives.csv")

dat %>% ggplot(aes(x=DiveHeartRate, y=(Duration)^2)) + geom_point() + stat_smooth(method = "lm", se = TRUE)
dat %>% ggplot(aes(x=DiveHeartRate, y=(Duration)^.5)) + geom_point() + stat_smooth(method = "lm", se = TRUE)
dat %>% ggplot(aes(x=DiveHeartRate, y=log(Duration))) + geom_point() + stat_smooth(method = "lm", se = TRUE)
```

### 6. Now fit the linear model again with the transformed data. Are the diagnostics better?

```{r lm-transformed}
out_transf = lm(formula = log(DiveHeartRate) ~ Duration, data = dat)
summary(out_transf)

plot(out)
plot(out_transf)
```


### 7. Explore the outliers.
```{r outliers}
dat[32,]

```

