---
title: "Review for Exam 2"
author: "Maria Cuellar"
date: "2024-11-6"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Review exercises 

```{r preamble}
library(tidyverse)
```

### 1. We will use the data that comes with R called "cars". What are the variables and their units? Do a quick EDA to see what they're like.

```{r load-data}
dat <- read_csv("data/crimerate_econstability.csv")

dat$crime_rate[50] <- 78
dat$crime_rate[45] <- 90
dat$crime_rate[17] <- 79

dat %>% ggplot(aes(x=crime_rate)) + geom_histogram(bins=10)
summary(dat$crime_rate)

dat %>% ggplot(aes(x=economic_stability)) + geom_histogram(bins=10)
summary(dat$economic_stability)

dat %>% ggplot(aes(x=economic_stability, y=crime_rate)) + geom_point()

write.csv(dat, "data/crimerate_econstability.csv")

out <- lm(crime_rate ~ economic_stability, data=dat)
library(MASS)
boxcox(out)



out.1 <- lm( 1/crime_rate ~ economic_stability, data=dat)
plot(out.1)

dat %>% ggplot(aes(x=economic_stability, y=1/crime_rate)) + geom_point()



dat %>% ggplot(aes(x=economic_stability, y=crime_rate)) + geom_point()

dat %>% ggplot(aes(x=economic_stability, y=log(crime_rate))) + geom_point()

out <- lm( crime_rate ~ economic_stability, data=dat)
out.transformed <- lm( log(crime_rate) ~ economic_stability, data=dat)

plot(out)
plot(out.transformed)

sort(dat$crime_rate)

dat
dat.no.outliers <- dat %>% filter(crime_rate < 75)
dat.no.outliers




dat.no.outliers %>% 
  ggplot(aes(x=economic_stability, y=crime_rate)) + geom_point()


out.no.outliers <- lm(crime_rate ~ economic_stability, data=dat.no.outliers)
summary(out.no.outliers)

plot(out.no.outliers)



```

Answer: 

For each additional unit of economic stability, the crime rate decreased by 0.20 units, and this is statistically significantly different from zero at the 0.05 level. 




